// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsp3YTiszzbrcSC_0hnpNDvAkpEG_6z2k',
    appId: '1:785719044452:web:26724b49850a68ebb2f271',
    messagingSenderId: '1000163153346',
    projectId: 'foryou-ride',
    authDomain: 'foryou-ride.firebaseapp.com',
    databaseURL: 'https://foryou-ride-default-rtdb.firebaseio.com',
    storageBucket: 'foryou-ride.appspot.com',
    measurementId: 'G-J8YWLHS06Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulOaJ9uL_KzhVtXmtuirWncHipJGyioA',
    appId: '1:785719044452:android:a371acf6634dbf51b2f271',
    messagingSenderId: '785719044452',
    projectId: 'foryou-ride',
    databaseURL: 'https://foryou-ride-default-rtdb.firebaseio.com',
    storageBucket: 'foryou-ride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxRDIuTc6ErANoftU-FtgLBSUxMlLCeA',
    appId: '1:1000163153346:ios:012d27ec8b417b2706b25b',
    messagingSenderId: '1000163153346',
    projectId: 'ammart-8885e',
    databaseURL: 'https://ammart-8885e-default-rtdb.firebaseio.com',
    storageBucket: 'ammart-8885e.appspot.com',
    androidClientId: '1000163153346-8h3825qftiorhelafakqhl559fubeteb.apps.googleusercontent.com',
    iosClientId: '1000163153346-mu5bujn5d21bt3vkii5lel4ihml97qmj.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxRDIuTc6ErANoftU-FtgLBSUxMlLCeA',
    appId: '1:1000163153346:ios:012d27ec8b417b2706b25b',
    messagingSenderId: '1000163153346',
    projectId: 'ammart-8885e',
    databaseURL: 'https://ammart-8885e-default-rtdb.firebaseio.com',
    storageBucket: 'ammart-8885e.appspot.com',
    androidClientId: '1000163153346-8h3825qftiorhelafakqhl559fubeteb.apps.googleusercontent.com',
    iosClientId: '1000163153346-mu5bujn5d21bt3vkii5lel4ihml97qmj.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );
}